/**
 * Generated by "@vuepress/internal-root-mixins"
 */
import m0 from "/Users/chenxiaodong/Documents/GitHub/erdong-notes/node_modules/_@vuepress_core@1.8.2@@vuepress/core/lib/client/root-mixins/updateMeta.js"
import m1 from "/Users/chenxiaodong/Documents/GitHub/erdong-notes/node_modules/_@vuepress_plugin-active-header-links@1.8.2@@vuepress/plugin-active-header-links/clientRootMixin.js"
import m2 from "/Users/chenxiaodong/Documents/GitHub/erdong-notes/node_modules/_@vuepress_plugin-nprogress@1.8.2@@vuepress/plugin-nprogress/clientRootMixin.js"
import m3 from "/Users/chenxiaodong/Documents/GitHub/erdong-notes/node_modules/_vuepress-plugin-smooth-scroll@0.0.3@vuepress-plugin-smooth-scroll/lib/clientRootMixin.js"
import m4 from "/Users/chenxiaodong/Documents/GitHub/erdong-notes/node_modules/_vuepress-plugin-zooming@1.1.8@vuepress-plugin-zooming/lib/clientRootMixin.js"

export default [
  m0,
  m1,
  m2,
  m3,
  m4
]