/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/Users/chenxiaodong/Documents/GitHub/erdong-notes/node_modules/_@vuepress_core@1.8.2@@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-5358e722",
    path: "/archives/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5358e722").then(next)
    },
  },
  {
    path: "/archives/index.html",
    redirect: "/archives/"
  },
  {
    path: "/@pages/archivesPage.html",
    redirect: "/archives/"
  },
  {
    name: "v-0cebcc02",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0cebcc02").then(next)
    },
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    path: "/@pages/categoriesPage.html",
    redirect: "/categories/"
  },
  {
    name: "v-2e8e39a2",
    path: "/tags/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2e8e39a2").then(next)
    },
  },
  {
    path: "/tags/index.html",
    redirect: "/tags/"
  },
  {
    path: "/@pages/tagsPage.html",
    redirect: "/tags/"
  },
  {
    name: "v-f3fec70e",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f3fec70e").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-34c9d17d",
    path: "/about/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-34c9d17d").then(next)
    },
  },
  {
    path: "/about/index.html",
    redirect: "/about/"
  },
  {
    name: "v-82cab74c",
    path: "/pages/78a5f0/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-82cab74c").then(next)
    },
  },
  {
    path: "/pages/78a5f0/index.html",
    redirect: "/pages/78a5f0/"
  },
  {
    path: "/interview/Html&CSS/CSS.html",
    redirect: "/pages/78a5f0/"
  },
  {
    name: "v-76145142",
    path: "/pages/0d0056/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-76145142").then(next)
    },
  },
  {
    path: "/pages/0d0056/index.html",
    redirect: "/pages/0d0056/"
  },
  {
    path: "/interview/Html&CSS/Html.html",
    redirect: "/pages/0d0056/"
  },
  {
    name: "v-8435e3fc",
    path: "/pages/27e97c/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8435e3fc").then(next)
    },
  },
  {
    path: "/pages/27e97c/index.html",
    redirect: "/pages/27e97c/"
  },
  {
    path: "/interview/Integration.html",
    redirect: "/pages/27e97c/"
  },
  {
    name: "v-a931c9c2",
    path: "/pages/3a4a94/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a931c9c2").then(next)
    },
  },
  {
    path: "/pages/3a4a94/index.html",
    redirect: "/pages/3a4a94/"
  },
  {
    path: "/interview/JS/Event Loop.html",
    redirect: "/pages/3a4a94/"
  },
  {
    name: "v-2076a518",
    path: "/pages/12cb22/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2076a518").then(next)
    },
  },
  {
    path: "/pages/12cb22/index.html",
    redirect: "/pages/12cb22/"
  },
  {
    path: "/interview/JS/PromiseAsyncAwait.html",
    redirect: "/pages/12cb22/"
  },
  {
    name: "v-9d1af5fc",
    path: "/pages/49eb26/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9d1af5fc").then(next)
    },
  },
  {
    path: "/pages/49eb26/index.html",
    redirect: "/pages/49eb26/"
  },
  {
    path: "/interview/JS/V8.html",
    redirect: "/pages/49eb26/"
  },
  {
    name: "v-145c61a4",
    path: "/pages/f86881/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-145c61a4").then(next)
    },
  },
  {
    path: "/pages/f86881/index.html",
    redirect: "/pages/f86881/"
  },
  {
    path: "/interview/Library/List.html",
    redirect: "/pages/f86881/"
  },
  {
    name: "v-16de60e2",
    path: "/pages/50ebbe/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-16de60e2").then(next)
    },
  },
  {
    path: "/pages/50ebbe/index.html",
    redirect: "/pages/50ebbe/"
  },
  {
    path: "/interview/Library/Questionlibrary.html",
    redirect: "/pages/50ebbe/"
  },
  {
    name: "v-6c1df683",
    path: "/pages/3ecb42/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6c1df683").then(next)
    },
  },
  {
    path: "/pages/3ecb42/index.html",
    redirect: "/pages/3ecb42/"
  },
  {
    path: "/interview/React/React Diff.html",
    redirect: "/pages/3ecb42/"
  },
  {
    name: "v-d3ab27fc",
    path: "/pages/2bcec2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d3ab27fc").then(next)
    },
  },
  {
    path: "/pages/2bcec2/index.html",
    redirect: "/pages/2bcec2/"
  },
  {
    path: "/interview/JavaScriptInterview.html",
    redirect: "/pages/2bcec2/"
  },
  {
    name: "v-45f121c7",
    path: "/pages/923ecd/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-45f121c7").then(next)
    },
  },
  {
    path: "/pages/923ecd/index.html",
    redirect: "/pages/923ecd/"
  },
  {
    path: "/interview/React/React Hook.html",
    redirect: "/pages/923ecd/"
  },
  {
    name: "v-55491698",
    path: "/pages/703160/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-55491698").then(next)
    },
  },
  {
    path: "/pages/703160/index.html",
    redirect: "/pages/703160/"
  },
  {
    path: "/interview/React/ReactFiber.html",
    redirect: "/pages/703160/"
  },
  {
    name: "v-625cb7e5",
    path: "/pages/01047f/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-625cb7e5").then(next)
    },
  },
  {
    path: "/pages/01047f/index.html",
    redirect: "/pages/01047f/"
  },
  {
    path: "/interview/React/Virtual DOM.html",
    redirect: "/pages/01047f/"
  },
  {
    name: "v-4909e8bc",
    path: "/pages/6a9523/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4909e8bc").then(next)
    },
  },
  {
    path: "/pages/6a9523/index.html",
    redirect: "/pages/6a9523/"
  },
  {
    path: "/interview/Webpack/webpack.html",
    redirect: "/pages/6a9523/"
  },
  {
    name: "v-c45e9e0c",
    path: "/pages/7b89ea/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c45e9e0c").then(next)
    },
  },
  {
    path: "/pages/7b89ea/index.html",
    redirect: "/pages/7b89ea/"
  },
  {
    path: "/note/Browser/EventLoop.html",
    redirect: "/pages/7b89ea/"
  },
  {
    name: "v-a71486fc",
    path: "/pages/f6701f/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a71486fc").then(next)
    },
  },
  {
    path: "/pages/f6701f/index.html",
    redirect: "/pages/f6701f/"
  },
  {
    path: "/note/Browser/V8.html",
    redirect: "/pages/f6701f/"
  },
  {
    name: "v-77a4e37c",
    path: "/pages/plantUml/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-77a4e37c").then(next)
    },
  },
  {
    path: "/pages/plantUml/index.html",
    redirect: "/pages/plantUml/"
  },
  {
    path: "/note/Daily/PlantUML.html",
    redirect: "/pages/plantUml/"
  },
  {
    name: "v-66f614ac",
    path: "/pages/javascript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-66f614ac").then(next)
    },
  },
  {
    path: "/pages/javascript/index.html",
    redirect: "/pages/javascript/"
  },
  {
    path: "/note/JavaScript/JavaScript基础.html",
    redirect: "/pages/javascript/"
  },
  {
    name: "v-609ed934",
    path: "/pages/e53db3/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-609ed934").then(next)
    },
  },
  {
    path: "/pages/e53db3/index.html",
    redirect: "/pages/e53db3/"
  },
  {
    path: "/note/MV*/React/ReactFirber.html",
    redirect: "/pages/e53db3/"
  },
  {
    name: "v-63397d7c",
    path: "/pages/a29bb7/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-63397d7c").then(next)
    },
  },
  {
    path: "/pages/a29bb7/index.html",
    redirect: "/pages/a29bb7/"
  },
  {
    path: "/note/MV*/React/ReactHooks.html",
    redirect: "/pages/a29bb7/"
  },
  {
    name: "v-9ee5cc90",
    path: "/pages/1f970b/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9ee5cc90").then(next)
    },
  },
  {
    path: "/pages/1f970b/index.html",
    redirect: "/pages/1f970b/"
  },
  {
    path: "/note/MV*/React/ReactVirtualDOM.html",
    redirect: "/pages/1f970b/"
  },
  {
    name: "v-38fd5eec",
    path: "/pages/context/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-38fd5eec").then(next)
    },
  },
  {
    path: "/pages/context/index.html",
    redirect: "/pages/context/"
  },
  {
    path: "/note/context.html",
    redirect: "/pages/context/"
  },
  {
    name: "v-432c973c",
    path: "/pages/0088df/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-432c973c").then(next)
    },
  },
  {
    path: "/pages/0088df/index.html",
    redirect: "/pages/0088df/"
  },
  {
    path: "/note/test.html",
    redirect: "/pages/0088df/"
  },
  {
    name: "v-9b4c403c",
    path: "/pages/9276fb/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9b4c403c").then(next)
    },
  },
  {
    path: "/pages/9276fb/index.html",
    redirect: "/pages/9276fb/"
  },
  {
    path: "/note/todo.html",
    redirect: "/pages/9276fb/"
  },
  {
    name: "v-6a10a6a2",
    path: "/pages/top-level-await/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6a10a6a2").then(next)
    },
  },
  {
    path: "/pages/top-level-await/index.html",
    redirect: "/pages/top-level-await/"
  },
  {
    path: "/note/top-levelAwait.html",
    redirect: "/pages/top-level-await/"
  },
  {
    name: "v-76ab9602",
    path: "/pages/typeScript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-76ab9602").then(next)
    },
  },
  {
    path: "/pages/typeScript/index.html",
    redirect: "/pages/typeScript/"
  },
  {
    path: "/note/typescript.html",
    redirect: "/pages/typeScript/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]