/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "前端指南",
  "description": "前端技术学习指南",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "type": "image/jpg",
        "href": "/js-nation-square-blue.png"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "actionText": "→ 开始阅读 ←",
        "actionLink": "/note/typescript.md",
        "features": [
          {
            "title": "Ecosystem",
            "details": "精通 VS Code、NodeJS、Webpack、Lottie 等软件与工具包的安装与卸载，配套设施也是必不可少的。"
          },
          {
            "title": "JavaScript",
            "details": "熟练掌握 React、TypeScript、Rax（H5）等单词的拼写，熟练使用ES6语法编程，追求代码高质量可维护性。"
          },
          {
            "title": "Motto",
            "details": "程序就像女人的裙子，越短才越好"
          }
        ],
        "footer": "Powered By VuePress | 2021 ErDong"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-f3fec70e",
      "path": "/",
      "lastUpdated": "Jul 27, 2021 8:09 PM"
    },
    {
      "title": "关于我",
      "frontmatter": {
        "title": "关于我",
        "date": "2021-07-26T13:44:36.000Z",
        "permalink": "/about/",
        "categories": [
          "about"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/about/",
      "relativePath": "about/README.md",
      "key": "v-34c9d17d",
      "path": "/about/",
      "headers": [
        {
          "level": 2,
          "title": "我自己",
          "slug": "wo-zi-ji"
        }
      ],
      "lastUpdated": "Jul 27, 2021 8:09 PM"
    },
    {
      "title": "优化使用context带来的不必要渲染问题",
      "frontmatter": {
        "title": "优化使用context带来的不必要渲染问题",
        "date": "2021-08-06T20:08:37.000Z",
        "permalink": "/pages/context/",
        "categories": [
          "note"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/note/context.html",
      "relativePath": "note/context.md",
      "key": "v-38fd5eec",
      "path": "/pages/context/",
      "headers": [
        {
          "level": 2,
          "title": "预览",
          "slug": "yu-lan"
        },
        {
          "level": 2,
          "title": "说明",
          "slug": "shuo-ming"
        },
        {
          "level": 2,
          "title": "Stage1",
          "slug": "stage1"
        }
      ],
      "lastUpdated": "Sep 7, 2021 10:55 PM"
    },
    {
      "title": "PlantUML",
      "frontmatter": {
        "title": "PlantUML",
        "date": "2021-09-07T20:53:43.000Z",
        "permalink": "/pages/plantUml/",
        "categories": [
          "note"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/note/Daily/PlantUML.html",
      "relativePath": "note/Daily/PlantUML.md",
      "key": "v-77a4e37c",
      "path": "/pages/plantUml/",
      "headers": [
        {
          "level": 2,
          "title": "Vuepress 增加 PlantUML 支持",
          "slug": "vuepress-zeng-jia-plantuml-zhi-chi"
        }
      ],
      "lastUpdated": "Sep 7, 2021 10:55 PM"
    },
    {
      "title": "top-level await",
      "frontmatter": {
        "title": "top-level await",
        "date": "2021-07-26T16:04:15.000Z",
        "permalink": "/pages/top-level-await/",
        "categories": [
          "note"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/note/top-levelAwait.html",
      "relativePath": "note/top-levelAwait.md",
      "key": "v-6a10a6a2",
      "path": "/pages/top-level-await/",
      "headers": [
        {
          "level": 2,
          "title": "top-level await",
          "slug": "top-level-await"
        },
        {
          "level": 3,
          "title": "1. 在引入 top-level await 之前",
          "slug": "1.-zai-yin-ru-top-level-await-zhi-qian"
        },
        {
          "level": 3,
          "title": "2.使用 Export Promise 来代替初始化",
          "slug": "2.shi-yong-export-promise-lai-dai-ti-chu-shi-hua"
        },
        {
          "level": 3,
          "title": "3. 使用 top-level await",
          "slug": "3.-shi-yong-top-level-await"
        },
        {
          "level": 3,
          "title": "4. 过去",
          "slug": "4.-guo-qu"
        },
        {
          "level": 3,
          "title": "5. 现在",
          "slug": "5.-xian-zai"
        },
        {
          "level": 3,
          "title": "6. 何时使用",
          "slug": "6.-he-shi-shi-yong"
        },
        {
          "level": 3,
          "title": "结尾",
          "slug": "jie-wei"
        }
      ],
      "lastUpdated": "Sep 7, 2021 10:55 PM"
    },
    {
      "title": "🚗 JavaScript基础篇",
      "frontmatter": {
        "title": "🚗 JavaScript基础篇",
        "date": "2021-09-07T20:02:54.000Z",
        "permalink": "/pages/javascript/",
        "categories": [
          "note"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/note/JavaScript/JavaScript%E5%9F%BA%E7%A1%80.html",
      "relativePath": "note/JavaScript/JavaScript基础.md",
      "key": "v-66f614ac",
      "path": "/pages/javascript/",
      "headers": [
        {
          "level": 2,
          "title": "👨🏻‍💻 导图",
          "slug": "dao-tu"
        },
        {
          "level": 2,
          "title": "📒 整理",
          "slug": "zheng-li"
        }
      ],
      "lastUpdated": "Sep 7, 2021 10:55 PM"
    },
    {
      "title": "typescript不完整指南",
      "frontmatter": {
        "title": "typescript不完整指南",
        "date": "2021-07-26T14:00:49.000Z",
        "permalink": "/pages/typeScript/",
        "categories": [
          "note"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/note/typescript.html",
      "relativePath": "note/typescript.md",
      "key": "v-76ab9602",
      "path": "/pages/typeScript/",
      "headers": [
        {
          "level": 2,
          "title": "1、为什么要学习 TypeScript",
          "slug": "1-wei-shi-me-yao-xue-xi-typescript"
        },
        {
          "level": 2,
          "title": "2、基础类型",
          "slug": "2-ji-chu-lei-xing"
        },
        {
          "level": 2,
          "title": "3、枚举",
          "slug": "3-mei-ju"
        },
        {
          "level": 2,
          "title": "4、函数 Function",
          "slug": "4-han-shu-function"
        },
        {
          "level": 2,
          "title": "5、断言",
          "slug": "5-duan-yan"
        },
        {
          "level": 2,
          "title": "6、接口 interface",
          "slug": "6-jie-kou-interface"
        },
        {
          "level": 2,
          "title": "7、类 Class",
          "slug": "7-lei-class"
        },
        {
          "level": 2,
          "title": "8、泛类 generic",
          "slug": "8-fan-lei-generic"
        },
        {
          "level": 2,
          "title": "9、高级类型",
          "slug": "9-gao-ji-lei-xing"
        },
        {
          "level": 2,
          "title": "10、tsconfig.json",
          "slug": "10-tsconfig.json"
        },
        {
          "level": 2,
          "title": "参考资源",
          "slug": "can-kao-zi-yuan"
        }
      ],
      "lastUpdated": "Sep 7, 2021 10:55 PM"
    },
    {
      "title": "JavaScript",
      "frontmatter": {
        "title": "JavaScript",
        "date": "2021-09-07T23:03:17.000Z",
        "permalink": "/interview/JavaScript/",
        "categories": [
          "interview"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/interview/JavaScript.html",
      "relativePath": "interview/JavaScript.md",
      "key": "v-d4b28010",
      "path": "/interview/JavaScript/"
    },
    {
      "title": "todo",
      "frontmatter": {
        "title": "todo",
        "date": "2021-09-07T22:28:49.000Z",
        "permalink": "/pages/9276fb/",
        "categories": [
          "note"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/note/todo.html",
      "relativePath": "note/todo.md",
      "key": "v-9b4c403c",
      "path": "/pages/9276fb/",
      "headers": [
        {
          "level": 3,
          "title": "📒 待整理",
          "slug": "dai-zheng-li"
        }
      ]
    },
    {
      "title": "分类",
      "frontmatter": {
        "categoriesPage": true,
        "title": "分类",
        "permalink": "/categories/",
        "article": false
      },
      "regularPath": "/@pages/categoriesPage.html",
      "relativePath": "@pages/categoriesPage.md",
      "key": "v-0cebcc02",
      "path": "/categories/",
      "lastUpdated": "Jul 26, 2021 2:08 PM"
    },
    {
      "title": "归档",
      "frontmatter": {
        "archivesPage": true,
        "title": "归档",
        "permalink": "/archives/",
        "article": false
      },
      "regularPath": "/@pages/archivesPage.html",
      "relativePath": "@pages/archivesPage.md",
      "key": "v-5358e722",
      "path": "/archives/",
      "lastUpdated": "Jul 26, 2021 2:08 PM"
    },
    {
      "title": "标签",
      "frontmatter": {
        "tagsPage": true,
        "title": "标签",
        "permalink": "/tags/",
        "article": false
      },
      "regularPath": "/@pages/tagsPage.html",
      "relativePath": "@pages/tagsPage.md",
      "key": "v-2e8e39a2",
      "path": "/tags/",
      "lastUpdated": "Jul 26, 2021 2:08 PM"
    }
  ],
  "themeConfig": {
    "author": {
      "name": "ErDong",
      "link": "https://github.com/MuBai1104"
    },
    "blogger": {
      "avatar": "https://tva1.sinaimg.cn/large/008i3skNly1gsueeuixx5j31400u0433.jpg",
      "name": "ErDong",
      "slogan": "略懂点前端"
    },
    "social": {
      "icons": [
        {
          "iconClass": "icon-github",
          "title": "GitHub",
          "link": "https://github.com/MuBai1104"
        }
      ]
    },
    "footer": {
      "createYear": 2021,
      "copyrightInfo": "ErDong | <a href=\"https://github.com/MuBai1104/erdong-notes/blob/master/LICENSE\" target=\"_blank\">MIT License</a>"
    },
    "bodyBgImg": [
      "https://images.unsplash.com/photo-1561160767-6bbd75de51b8?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2851&q=80"
    ],
    "bodyBgImgOpacity": 0.1,
    "contentBgStyle": 6,
    "lastUpdated": "上次更新",
    "nav": [
      {
        "text": "指南",
        "link": "/note/typescript"
      },
      {
        "text": "Interview",
        "link": "/interview/JavaScript"
      },
      {
        "text": "关于我",
        "link": "/about/"
      },
      {
        "text": "归档",
        "link": "/archives/"
      }
    ],
    "repo": "MuBai1104/erdong-notes",
    "sidebarDepth": 3,
    "sidebar": {
      "/note": [
        {
          "title": "JavaScript 语言",
          "children": [
            "/note/JavaScript/JavaScript基础.md"
          ],
          "collapsable": false
        },
        {
          "title": "其他语言",
          "children": [
            "/note/typescript.md"
          ],
          "collapsable": false
        },
        {
          "title": "瞎写",
          "children": [
            "/note/top-levelAwait.md",
            "/note/context.md"
          ],
          "collapsable": false
        },
        {
          "title": "开发生活/杂谈",
          "children": [
            "/note/Daily/PlantUML.md"
          ],
          "collapsable": false
        }
      ],
      "/interview": [
        {
          "title": "JavaScript 语言",
          "children": [
            "/note/JavaScript/JavaScript基础.md"
          ],
          "collapsable": false
        },
        {
          "title": "其他语言",
          "children": [
            "/note/typescript.md"
          ],
          "collapsable": false
        },
        {
          "title": "瞎写",
          "children": [
            "/note/top-levelAwait.md",
            "/note/context.md"
          ],
          "collapsable": false
        },
        {
          "title": "开发生活/杂谈",
          "children": [
            "/note/Daily/PlantUML.md"
          ],
          "collapsable": false
        }
      ],
      "/about": false
    }
  }
}